.\" xclip.1 - xclip manpage
.\" Copyright (C) 2021 Guilherme Janczak
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.Dd December 27, 2024
.Dt XCLIP 1
.Os
.Sh NAME
.Nm xclip
.Nd command line interface to X selections (clipboard)
.Sh SYNOPSIS
.Nm
.Op Fl fhior
.Op Fl d Ar display
.Op Fl l Ar loops
.Op Fl t Ar atom
.Op Fl alt-text Ar text
.Op Fl noutf8
.Op Fl version
.Op Fl silent | quiet | verbose
.Op Fl selection Cm primary | secondary | clipboard
.Op Fl sensitive | Fl wait Ar milliseconds
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility reads from stdin, or from one or more files,
and makes the data available as an X selection for pasting into X applications.
It reads from all files specified in the order of the arguments,
or from stdin if no files are specified.
If a
.Ar file
is a single dash
.Po Qo Sy - Qc Pc ,
then it is read from stdin.
.Pp
The default action is to silently wait in the background,
listening for X selection requests (pastes),
until another X application places data in the clipboard.
.Pp
Options can be abbreviated as long as they remain unambiguous.
For example, it's possible to use
.Fl d
or
.Fl disp
instead of
.Fl display .
However,
.Fl v
can't be used because it could be either of
.Fl verbose
or
.Fl version ,
in which case
.Fl v
would be interpreted as a filename.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl alt-text Ar text
Specify an alternative
.Ar text
to put into the target atom "STRING".
Some applications refuse to paste text unless this atom is provided in addition
to other text targets such as "text/html".
.It Fl d Ar display , Fl display Ar display
X display to use (e.g. "localhost:0"),
.Nm
defaults to the value in $DISPLAY if this option is omitted.
.It Fl f , filter
When
.Nm
is invoked with the
.Fl i
and
.Fl silent
options (the defaults), the
.Fl f
option will cause
.Nm
to copy stdin to stdout unmodified.
.It Fl h , help
Show a quick summary of the options.
.It Fl i , in
Read text into the X selection from standard input or files (default).
.It Fl l Ar loops , Fl loops Ar loops
Number of X selection requests (pastes into X applications) to wait for.
A value of 0 (default) causes
.Nm
to wait for an unlimited number of requests,
or until another X application takes ownership of the selection.
.It Fl noutf8
Operate in legacy (i.e. non UTF-8) mode.
This option exists for backwards compatibility only,
it should not be used otherwise.
.It Fl o , out
Print the selection to stdout.
.It Fl quiet
Show informational messages on the terminal and run in the foreground.
.It Fl r , rmlastnl
If the last character of the selection is a newline, remove it.
.It Fl selection Cm primary | secondary | clipboard
Specify the X selection to use.
Only the first character of the argument is significant,
thus
.Cm p
is equivalent to
.Cm primary ,
.Cm sec
is equivalent to
.Cm secondary ,
and
.Cm cl
is equivalent to
.Cm clipboard .
.It Fl sensitive
Clear the selection buffer after pasting once.
.It Fl silent
Fork into the background to wait for requests, only output errors (default).
.It Fl t Ar atom , Fl target Ar atom
Specify a particular format using the given target
.Ar atom .
With
.Fl o ,
the special
.Ar atom
name "TARGETS" will produce a list of valid
.Ar atom Ns s
for this selection.
The default target is "STRING".
For more information about target atoms refer to ICCCM section 2.6.2.
.It Fl verbose
Provide a running commentary of what
.Nm
is doing.
.It Fl version
Show version information.
.It Fl wait Ar milliseconds
After the first paste, a timer counts down from the specified time.
If a subsequent paste arrives before the timer expires, reset the timer.
Once the timer expires, the selection is cleared.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Place the uptime into the X selection:
.Dl $ uptime | xclip
.Pp
Put the contents of the selection into a file:
.Dl $ xclip -o > helloworld.c
.Pp
Exit after /etc/motd has been pasted 10 times,
and show how many selection requests (pastes) have been processed:
.Dl $ xclip -l 10 -verbose /etc/motd
.Pp
Take a screenshot and copy it to the clipboard:
.Dl $ scrot -e 'xclip -selection clipboard -t image/png -i $f'
.Sh AUTHORS
.An Kim Saunders Aq Mt kims@debian.org
.An Peter Åstrand Aq Mt astrand@lysator.liu.se
.An Guilherme Janczak Ao Mt guilherme.janczak@yandex.com Ac Po this manual Pc
.Sh BUGS
.Fl sensitive
is currently implemented as
.Fl wait
50.
.Pp
Open an issue or a pull request at
.Lk https://github.com/astrand/xclip
