.\" 
.\"
.\" xclip.man - xclip manpage
.\" Copyright (C) 2001 Kim Saunders
.\" Copyright (C) 2007-2020 Peter Åstrand
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.
.\" URL and email definitions from groff's an-ext.tmac file, just in
.\" case we're on a system with "classic" troff.
.
.\" Start URL.
.de UR
.  ds m1 \\$1\"
.  nh
.  if \\n(mH \{\
.    \" Start diversion in a new environment.
.    do ev URL-div
.    do di URL-div
.  \}
..
.
.
.\" End URL.
.de UE
.  ie \\n(mH \{\
.    br
.    di
.    ev
.
.    \" Has there been one or more input lines for the link text?
.    ie \\n(dn \{\
.      do HTML-NS "<a href=""\\*(m1"">"
.      \" Yes, strip off final newline of diversion and emit it.
.      do chop URL-div
.      do URL-div
\c
.      do HTML-NS </a>
.    \}
.    el \
.      do HTML-NS "<a href=""\\*(m1"">\\*(m1</a>"
\&\\$*\"
.  \}
.  el \
\\*(la\\*(m1\\*(ra\\$*\"
.
.  hy \\n(HY
..
.
.
.\" Start email address.
.de MT
.  ds m1 \\$1\"
.  nh
.  if \\n(mH \{\
.    \" Start diversion in a new environment.
.    do ev URL-div
.    do di URL-div
.  \}
..
.
.
.\" End email address.
.de ME
.  ie \\n(mH \{\
.    br
.    di
.    ev
.
.    \" Has there been one or more input lines for the link text?
.    ie \\n(dn \{\
.      do HTML-NS "<a href=""mailto:\\*(m1"">"
.      \" Yes, strip off final newline of diversion and emit it.
.      do chop URL-div
.      do URL-div
\c
.      do HTML-NS </a>
.    \}
.    el \
.      do HTML-NS "<a href=""mailto:\\*(m1"">\\*(m1</a>"
\&\\$*\"
.  \}
.  el \
\\*(la\\*(m1\\*(ra\\$*\"
.
.  hy \\n(HY
..
.
.TH XCLIP 1
.SH NAME
xclip \- command line interface to X selections (clipboard)
.SH SYNOPSIS
.B xclip
[OPTION] [FILE]...
.SH DESCRIPTION
Copies from standard input, or from one or more files, and makes the data
available as an X selection for pasting into X applications.
Pastes current X selection to standard out.
.TP
\fB\-i\fR, \fB\-in\fR
.
Copy text into X selection from standard input or files. (Default unless it
would read from a tty.)
.TP
\fB\-o\fR, \fB\-out\fR
.
Paste the selection to standard out. (Default when no files are specified and
standard input is a tty.)
.TP
\fB\-f\fR, \fB\-filter\fR
.
Copy text into the X selection and also print it out to standard out,
unmodified. Handy for pipelines. This does not (yet) work with files for input.
Not compatible with verbosity levels above \(lqsilent\(rq (the default) as
xclip would not exit after making the copy and could hang a pipeline.
.TP
\fB\-selection\fR \fIselection\fR
.
Specify which X selection to use, options are PRIMARY (default),
CLIPBOARD, or SECONDARY. See discussion in
\fBAbout Selections\fP
below.
.TP
\fB\-c\fR, \fB\-clipboard\fR
Shorthand for \(lq-selection clipboard\(rq. 
.TP
\fB\-t\fR \fIfmt\fR, \fB\-target\fR \fIfmt\fR
.
Specify a particular data format to request (out mode) or advertise (in mode)
using the given target \fIfmt\fR (e.g., image/jpeg). The default target is
UTF8_STRING. If, during output, that is not available, xclip will fallback to
STRING.
.
Note: xclip can only specify one target data format.
.
.TP
\fB\-T\fR, \fB\-TARGETS\fR
.
Show all formats that the current selection owner is willing to send for an
output (paste). Use this to pick a format for \fB-t\fR \fIfmt\fR.
.TP
\fB\-r\fR, \fB\-rmlastnl\fR
.
If the last character of the selection is a newline, remove it. Newline
characters that are not the last character in the selection are not affected.
If the selection does not end with a newline character, this option has no
effect. This option is useful for copying one-line output of programs like
\fBpwd\fR to the clipboard to paste it again into the command prompt without
executing the line immediately due to the newline character \fBpwd\fR appends.
Can be used on input or ouput.
.TP
\fB\-loops\fR \fIn\fP
.
Given a natural number \fIn\fP, wait for \fIn\fP selection requests (pastes)
before clearing the selection and exiting. A value of 0 (default) causes xclip
to wait for an unlimited number of requests until another application \[em]
possibly another invocation of xclip \[em] takes ownership of the selection
(performs a copy). Input mode only.
.
.TP
\fB\-display\fR \fIdpy:n\fR
.
X display to use (e.g. \(lqlocalhost:0\(rq). If omitted, xclip defaults to the value in
$\fBDISPLAY\fR.
.TP
\fB\-h\fR, \fB\-help\fR
Show quick summary of options
.TP
\fB\-V\fR, \fB\-version\fR
Show version information.
.TP
\fB\-silent\fR
.
Errors only, no informational output. (Default). In input mode (copy), forks
a background process to wait for requests and returns to command line.
.TP
\fB\-quiet\fR
Run in the foreground and show informational messages on the terminal.
.TP
\fB\-v\fR, \fB\-verbose\fR
Run in the foreground and provide a running commentary of what xclip is doing.
.TP
\fB\-debug\fR
Run in the foreground and print garrulous debugging output.
.TP
\fB\-sensitive\fR
.
Clear sensitive data from selection buffer after being pasted once.
This is currently implemented as \fB-wait 50\fP. See \fBNOTES\fR
.TP
\fB\-wait\fR \fIn\fR
.
After the first paste, wait for \fIn\fR milliseconds. If a subsequent paste
request arrives before the timer expires, reset the timer. Once the timer
expires, the selection buffer is cleared so the data cannot be pasted again.
.
.TP
\fB\-noutf8\fR
Operate in legacy (i.e. non UTF-8) mode for backwards compatibility.
(Use this option only when really necessary, as the old behavior was broken).
.
.PP
Xclip was designed to allow tighter integration of X applications and command
line programs. Xclip can be in either input mode (copy) or output mode (paste)
and will typically do the right thing without needing \fB-i\fP or \fB-o\fP to
be specified. Filenames on the commandline are always used for input. When the
input is from a file or a pipeline, xclip copies text (or binary data) in to
the X selection and forks a daemon to makes the data available to other X
applications for pasting. When no input is detected, or if \fB-o\fP is used,
xclip will print the contents of the current selection to standard output. This
is commonly piped into other commands, redirected to a file, or used in command
substitution. This is the default when no files are specified and stdin is a
tty (the user's keyboard).

The default action for \fB-in\fP (copy) is to silently fork a temporary daemon
and appear to exit immediately. The daemon waits in the background for X
selection requests (pastes) and sends the data to other applications. Xclip's
daemon exits silently when another X application performs a copy (technically,
when xclip \(lqloses ownership of the selection\(rq). One can use the
\fB\-verbose\fR option to prevent xclip from backgrounding itself to see if and
when it receives selection requests from other X applications.

Options can be abbreviated as long as they remain unambiguous. For example, it
is possible to use \fB\-d\fR or \fB\-disp\fR instead of \fB\-display\fR as no
other option begins with the letter 'd'. Any single character option listed in
this manual, will also work, even if ambiguous. For example, \fB\-v\fR will
always be short for \fB\-verbose\fR (rather than the less useful
\fB\-version\fR). Due to a fluke, using an ambiguous option, or forgetting to
include a mandatory argument, will give an elliptical response: \(lqNo such
file or directory.\(rq

Note that only the first character of the selection specified with the
\fB\-selection\fR option is important. This means that \(lqp\(rq, \(lqsec\(rq
and \(lqclip\(rq would have the same effect as using PRIMARY,
SECONDARY or CLIPBOARD respectively.

.SS About selections

The X Windowing System differs from Apple MacOS\(tm and Microsoft Windows\(tm
in that there are multiple clipboards (called \(lqselections\(rq) available.
Only two are in common use nowadays. The \fBPRIMARY\fP selection (the default
in xclip) is mainly used for quick text transfers. For example, highlighting
with a mouse does an implicit copy to PRIMARY in most applications and,
traditionally, the middle mouse button does a paste.

The \fBCLIPBOARD\fP selection is for data explicitly copied by the user,
including binary objects, such as images. Applications use the CLIPBOARD when
copying with menu options or the keyboard (Control-C / Control-V). Xclip allows
the shortcut \fB-c\fP to mean \fB-selection\fP \fBclipboard\fP. (Ecumenically,
xclip also accepts \fIxsel\fP's \fB-b\fP option as a synonym for \fB-c\fP).

.SS About targets

Each selection in X can have multiple \(lqtargets\(rq available. Each target is
a different data format. For example, a single clipboard selection might be
available as UTF8_STRING, STRING, text/html, image/jpeg, and application/pdf.
Which targets are available and what they mean is up to the copying
application. When multiple targets are available, the application that did the
copy provides a list of targets (data types) that it is willing to convert to
upon request. In xclip, one can see all targets currently available for pasting
with \fB-T\fP and pick one with \fB-t\fP.

When setting the selection (copying), xclip can only specify a single target
per selection. (This may change in the future). If no target is specified, then
xclip's default is UTF8_STRING. 

For more information about target atoms refer to ICCCM section 2.6.2.

.SH EXAMPLES
.TP
.B echo \[aq]I love man pages with examples!\[aq] | xclip
.IP
Copy a string into the PRIMARY selection.
Then middle click in an X application to paste.
.
.TP
.B pwd | xclip \-r
.IP
Middle click will paste the current working directory, but without the
trailing newline.
.
.TP
.B xclip
.IP
Print the PRIMARY selection to the screen.
.
.TP
.B xclip foo.txt
.IP
Read the file foo.txt and copy it into the PRIMARY selection. 
.
.TP
.B xclip > helloworld.c
.IP
Paste the PRIMARY selection into the file helloworld.c.
.
.TP
.B xclip | figlet | xclip
.IP
Change the PRIMARY selection into an ASCII art banner of the original text.
.EX
.vs 1m			\" No extra vertical line spacing 
.tr , \"		\" Translate comma to space
,,,,,,,,,,_,_,,,,,,,,,_,,,,__,_,,,,,,,_,,,,,,_,,,
__,,_____|,(_)_,__,,,|,|,,/,_(_),__,_|,|,___|,|_,
\\,\\/,/,__|,|,|,'_,\\,,|,|,|,|_|,|/,_`,|,|/,_,\\,__|
,>,,<,(__|,|,|,|_),|,|,|,|,,_|,|,(_|,|,|,,__/,|_,
/_/\\_\\___|_|_|,.__/,,|,|,|_|,|_|\\__,,|_|\\___|\\__|
,,,,,,,,,,,,,|_|,,,,,|_|,,,,,,,,|___/,,,,,,,,,,,,
.tr ,, \"		\" Reset comma
.vs			\" Reset vertical spacing
.EE
.
.TP
.B youtube-dl \[dq]$(xclip)\[dq]
.IP
Download the video at the URL selected by the mouse. (Requires youtube-dl). 
.
.TP
.B xclip \-t text/html index.html
.IP
Copy a file with a specific MIME type. Middle click in an X application
supporting HTML to paste the contents of the given file as HTML.
.
.TP
.B xclip \-c \-t image/jpeg foo.jpg
.IP
Copy an image to the clipboard. Now it is possible to paste it into a graphical
application using Control-V.
.
.TP
.B xclip \-c \-t $(file \-\-brief \-\-mime-type foo) foo
.IP
Copy a file named \(lqfoo\(rq, advertising the target format to be the same as
the file's MIME filetype.
.
.TP
.B xclip \-c \-T
.IP
List valid data formats available on the clipboard. For example, after doing
Right Click \[->] Copy Image in a web browser, one might see:
.
.EX
.RS
.RS
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
text/html
image/png
image/tiff
image/jpeg
.RE
.EE
.
Note that in this case the text/html target is the HTML source code that
embedded the image on the page.
.RE
.TP
.B xclip \-c \-t image/jpeg > bar.jpg
.IP
Paste an image from the clipboard to a file.
.
.TP
.B xclip \-t image/jpeg | convert \-geometry \[aq]>800x>480\[aq] \- sixel:-
.IP
Show the image from the clipboard in a terminal which handles sixel graphics
(e.g., \fIxterm\~-ti\~vt340\fP). 
.
.TP
.B xclip \-loops 10 \-verbose /etc/motd
.IP
Exit after /etc/motd (message of the day) has been pasted 10 times. Show how
many selection requests (pastes) have been processed.
.
.TP
.B xclip \
|\~sed\~\-E\~\[aq]\
s/\[dq](\[rs]s|$)|\[rs]b\[dq]/\[rs]xE2\[rs]x80\[rs]x9D\[rs]1/g;\~\
s/\[dq]\[rs]b|(\[rs]s)\[dq]/\[rs]1\[rs]xE2\[rs]x80\[rs]x9C/g\[aq] \
| xclip\~\-f | xclip\~\-c
.IP
Modify the selection so that plain ASCII quotes\~(\[dq]) are
replaced with left\~(\[lq]) or right\~(\[rq]) quotes, as appropriate. The
result is copied to both the PRIMARY and CLIPBOARD so that text that has been
highlighted with the mouse can be easily replaced with Control-V (paste).

.SH USAGE NOTES

.SS Sensitive data

Using the \fB\-sensitive\fR option will clear the selection buffer of the
sensitive information 50 milliseconds after it has been pasted, effectively only
allowing the selection to be pasted once. In some instances this may be too low
and will prevent pasting. If this is the case, or if the user needs to be able
to paste more than once for some other reason, they may use \fB\-wait\fR \fIn\fR
instead. \fB\-wait\fR is the same as \fB\-sensitive\fR, except it allows one to
adjust the time to wait before clearing the selection to be \fIn\fR
milliseconds.
.PP
Ideally, \fB\-sensitive\fR would allow exactly one paste and not need a
timeout, but due to subtleties in the way the X clipboard protocol works, doing
so is not as simple as it may seem.

.SS SECONDARY and BUFFERCUT selections
Historically, there were other selections such as SECONDARY and BUFFERCUT. Very
few applications nowadays make use of them. They are fully supported by Xclip,
if you so desire. For example, to swap the PRIMARY and SECONDARY selections,
you could do this:

.EX
$ xclip \-sel s | xclip \-sel b
$ xclip | xclip \-sel s
$ xclip \-sel b | xclip
.EE

Note that the BUFFERCUT selection uses an older transfer method and has
various limitations, such as, inability to choose a TARGET and a maximum
amount of data (\[~=] 16 MB).

.SH ENVIRONMENT
.TP
.SM
\fBDISPLAY\fR
X display to use if none is specified with the
.B
\-display
option.

.SH SEE ALSO
.PP
.IR xclip-copyfile (1),
.IR xclip-cutfile  (1),
and
.IR xclip-pastefile (1)
copy and move files via the X clipboard.
.PP
.IR xsel (1)
and
.IR wl-clipboard (1)
are command line programs similar to xclip. xsel only works with text, but has
the ability to keep a primary selection even after a program has closed.
wl-clipboard works with Wayland instead of X.
.PP
.IR clipit (1),
.IR copyq (1),
.IR diodon (1),
.IR gpaste (1),
.IR qlipper (1),
.IR xfce4-clipman (1)
and
.IR xclipboard (1)
are just a few of many, many GUI clipboard managers which let you browse your
clipboard's history.
.PP
.UR https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html
ICCCM: The Inter-Client Communication Conventions Manual
.UE


.SH KNOWN BUGS
.PP
xclip is not fully ICCCM compliant. For example, the TIMESTAMP isn't set and
MULTIPLE does not work.
.PP
Only one target type can be chosen. It would be useful to let users pick a
different type for each input file.
.PP
Making users specify the MIME type of files by hand is silly. Xclip ought to be
able to automatically set the target appropriately using `file \-\-brief
\-\-mime-type` on any files provided on the command line.
.PP
Xclip cannot automatically convert between data types. For example, if the user
has specified \fB-t image/png\fP as input, xclip will not correctly handle a
request for a different target, such as \(lqimage/jpeg\(rq. Currently xclip
sends the same data willy-nilly regardless of what was requested. It ought to,
at the least, return an error if it cannot comply.

.SH REPORTING BUGS
Please report any bugs, problems, queries, experiences, etc. directly to the
author or at
.UR https://github.com/astrand/xclip/issues
github.
.UE
.SH AUTHORS
.MT astrand@lysator.liu.se
Peter \(oAstrand
.ME
.br
.MT kims@debian.org
Kim Saunders 
.ME
